# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: Install gitbook
    init: | 
      # nvm install v13.14.0
      # nvm install v12.18.2
      nvm install v8.8 # gulpとコンパチブルなバージョン
      # nvm install v7.2 # nvm ls-remote
      npm install -g gitbook-cli
      npm install -g xmlhttprequest
      # npm install -g gulp@3.9.1
      # npm install browser-sync
      # npm install del
      # mkdir docs
      # cd docs
      gitbook install -g advanced-emoji
      gitbook install -g hints     # https://www.npmjs.com/package/gitbook-plugin-hints
      # gitbook install -g todo  Error: Missing required argument #1 if (args[ii] == null) throw missingRequiredArg(ii)
      # gitbook install -g mathjax
      gitbook install -g tabs2
      gitbook install -g url-embed # https://www.npmjs.com/package/gitbook-plugin-url-embed
      gitbook install -g hide-published-with
      # gitbook install -g sunlight-highlighter
      gitbook install -g anchors
      # gitbook install -g theme-official theme-open-docs theme-busbud
      gitbook install -g codeblock-label
      gitbook install -g search-pro-kui
      gitbook install -g code
      gitbook install -g youtube-placeholder
      gitbook install -g graph katex amazon-jp-link mind-maps
      gitbook init
      # gulp
      gitbook serve
    command: echo 'Ready to start'

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 4000
    onOpen: open-preview
