# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: Install gitbook
    init: | 
      nvm install v13.14.0
      # nvm install v12.18.2 # nvm ls-remote
      npm install -g gitbook-cli@v2.6.9
      # npm install gulp
      # npm install browser-sync
      # npm install del
      # mkdir docs
      # cd docs
      gitbook init
      # gulp
      gitbook serve
    command: echo 'Ready to start'

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 4000
    onOpen: open-preview
